services:
  - type: web
    name: eye-catchers-salon
    env: node
    nodeVersion: 18.19.1
    buildCommand: |
      npm install --legacy-peer-deps
      npm install -g next
      npm install -g tailwindcss postcss autoprefixer
      npx tailwindcss init -p
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 