services:
  - type: web
    name: eye-catchers-salon
    env: node
    nodeVersion: 18.19.1
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 